-- =============================================================================
-- Trendlines + Key Levels + Bounce Catcher schema
-- Adds tables for market structure analysis and bounce event tracking.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 1) market_pivots — atomic structural events (fractal highs/lows)
-- ---------------------------------------------------------------------------
create table if not exists public.market_pivots (
  id         bigint generated by default as identity primary key,
  symbol     text        not null,
  timeframe  text        not null,
  timestamp  timestamptz not null,
  price      numeric     not null,
  type       text        not null check (type in ('high', 'low')),
  source     text        not null check (source in ('wick', 'body')),
  atr_snapshot numeric,
  confirmed  boolean     not null default true,
  created_at timestamptz not null default now(),
  unique (symbol, timeframe, timestamp, type, source)
);

create index if not exists idx_pivots_lookup
  on public.market_pivots (symbol, timeframe, timestamp desc);

create index if not exists idx_pivots_type_source
  on public.market_pivots (symbol, timeframe, type, source);


-- ---------------------------------------------------------------------------
-- 2) technical_trendlines — RANSAC-fitted support/resistance lines
-- ---------------------------------------------------------------------------
create table if not exists public.technical_trendlines (
  id           bigint generated by default as identity primary key,
  symbol       text        not null,
  timeframe    text        not null,
  side         text        not null check (side in ('support', 'resistance')),
  slope        numeric     not null,
  intercept    numeric     not null,
  start_at     timestamptz not null,
  end_at       timestamptz not null,
  inlier_count int         not null,
  score        numeric     not null default 0,
  metadata     jsonb       not null default '{}'::jsonb,
  is_active    boolean     not null default true,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create index if not exists idx_trendlines_lookup
  on public.technical_trendlines (symbol, timeframe, is_active, updated_at desc);


-- ---------------------------------------------------------------------------
-- 3) technical_levels — DBSCAN-clustered horizontal S/R zones
-- ---------------------------------------------------------------------------
create table if not exists public.technical_levels (
  id             bigint generated by default as identity primary key,
  symbol         text        not null,
  timeframe      text        not null,
  price_centroid numeric     not null,
  price_top      numeric     not null,
  price_bottom   numeric     not null,
  role           text        check (role in ('support', 'resistance', 'flip')),
  touch_count    int         not null default 0,
  score          numeric     not null default 0,
  first_tested   timestamptz,
  last_tested    timestamptz,
  is_active      boolean     not null default true,
  metadata       jsonb       not null default '{}'::jsonb,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

create index if not exists idx_levels_lookup
  on public.technical_levels (symbol, timeframe, is_active, score desc);

create index if not exists idx_levels_price_range
  on public.technical_levels (symbol, timeframe, price_bottom, price_top);


-- ---------------------------------------------------------------------------
-- 4) structure_events — breakout / breakdown / retest events
-- ---------------------------------------------------------------------------
create table if not exists public.structure_events (
  id            bigint generated by default as identity primary key,
  symbol        text        not null,
  timeframe     text        not null,
  event_type    text        not null check (event_type in ('breakout', 'breakdown', 'retest')),
  reference_id  bigint,                           -- FK to trendlines or levels
  reference_kind text       check (reference_kind in ('trendline', 'level')),
  price_at      numeric     not null,
  confirmed     boolean     not null default false,
  confirm_count int         not null default 0,   -- consecutive closes past
  reason_json   jsonb       not null default '{}'::jsonb,
  ts            timestamptz not null default now()
);

create index if not exists idx_structure_events_lookup
  on public.structure_events (symbol, timeframe, ts desc);


-- ---------------------------------------------------------------------------
-- 5) bounce_events — state machine transitions for bounce catcher
-- ---------------------------------------------------------------------------
create table if not exists public.bounce_events (
  id          uuid        primary key default gen_random_uuid(),
  ts          timestamptz not null default now(),
  symbol      text        not null,
  prev_state  text,
  state       text        not null,
  score       integer,
  reason_json jsonb       not null default '{}'::jsonb
);

create index if not exists idx_bounce_events_symbol_ts
  on public.bounce_events (symbol, ts desc);


-- ---------------------------------------------------------------------------
-- 6) bounce_intents — trade intents emitted or blocked by bounce catcher
-- ---------------------------------------------------------------------------
create table if not exists public.bounce_intents (
  id               uuid    primary key default gen_random_uuid(),
  ts               timestamptz not null default now(),
  symbol           text    not null,
  entry_style      text    check (entry_style in ('retest', 'breakout')),
  entry_price      numeric,
  expected_move_pct numeric,
  tp_price         numeric,
  sl_price         numeric,
  score            integer,
  components_json  jsonb   not null default '{}'::jsonb,
  blocked          boolean not null default false,
  blocked_reason   text,
  executed         boolean not null default false,
  reason_json      jsonb   not null default '{}'::jsonb
);

create index if not exists idx_bounce_intents_symbol_ts
  on public.bounce_intents (symbol, ts desc);
